name: Generate README on datasets.csv file update

on:
  pull_request:
    branches:
      - main
    paths:
      - "datasets.csv"

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas tabulate

      - name: Reorder datasets.csv and generate README
        run: |
          python generate_datasets_table.py

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add datasets.csv README.md
          git commit -m "Update datasets table and reorder datasets.csv"
          git push --force origin HEAD:${{ github.head_ref }}
